[[redirects]]
  from = "/proxy/*"
  to = "http://ec2-13-125-172-34.ap-northeast-2.compute.amazonaws.com:8080/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200